#pragma checksum "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2630b74ff4bf18ce523e94f21440137f425b4b25"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_UserManager_UserManager), @"mvc.1.0.view", @"/Views/UserManager/UserManager.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\Usuario\source\repos\Doctor2.0\Views\_ViewImports.cshtml"
using Doctor2._0;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\Usuario\source\repos\Doctor2.0\Views\_ViewImports.cshtml"
using Doctor2._0.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2630b74ff4bf18ce523e94f21440137f425b4b25", @"/Views/UserManager/UserManager.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"48bb3f799a1396cd4dd4db6d04f157e29d8a6b5c", @"/Views/_ViewImports.cshtml")]
    public class Views_UserManager_UserManager : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("onclick", new global::Microsoft.AspNetCore.Html.HtmlString("stopDefAction(event);"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "2", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "1", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "3", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "0", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/js/user.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<!--<span class=""right badge badge-danger"">New</span>-->
<div class=""content-wrapper"">
    <!-- Content Header (Page header) -->
    
        <div class=""container-fluid"">

            <!-- Button trigger modal -->
            <button type=""button"" class=""btn btn-primary"" data-toggle=""modal"" data-target=""#UserModal"">
                Crear Usuarios
            </button>


        </div><!-- /.container-fluid -->
        <br />
        <div id=""messageSuccess"" class=""text-center text-bold""></div>
        <div class=""row"">
                <div class=""col-6"">
                    <div class=""table-responsive"">
                        <table class=""table"" id=""idTable"">
                            <caption>Lista de Doctores</caption>
                            <thead>

                                <tr>
                                    <th scope=""col"">Nombre</th>
                                    <th scope=""col"">Apellido</th>
                                    <th scope=""col"">Usuari");
            WriteLiteral(@"o</th>
                                    <th scope=""col"">Rol</th>
                                    <th scope=""col"">Editar</th>
                                    <th scope=""col"">Eliminar</th>
                                </tr>
                            </thead>
                            <tbody id=""itemTable"">
");
#nullable restore
#line 33 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                 if (ViewBag.listingDoctor != null)
                                {


                                    

#line default
#line hidden
#nullable disable
#nullable restore
#line 37 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                     foreach (var item in ViewBag.listingDoctor)
                                    {


#line default
#line hidden
#nullable disable
            WriteLiteral("                                <tr>\r\n\r\n                                    <td");
            BeginWriteAttribute("id", " id=\"", 1665, "\"", 1670, 0);
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 42 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                         Write(item.NameDoctor);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                                    <td");
            BeginWriteAttribute("id", " id=\"", 1734, "\"", 1739, 0);
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 43 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                         Write(item.LastNameDoctor);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                                    <td");
            BeginWriteAttribute("id", " id=\"", 1807, "\"", 1812, 0);
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 44 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                         Write(item.UserName);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                                    <td");
            BeginWriteAttribute("id", " id=\"", 1874, "\"", 1879, 0);
            EndWriteAttribute();
            WriteLiteral(">\r\n");
#nullable restore
#line 46 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                         if (item.IdRol == 2)
                                        {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                            <span class=\"right badge badge-primary\">Doctor</span>\r\n");
#nullable restore
#line 49 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                        }

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                    </td>\r\n                                    <td>\r\n\r\n                                        <button");
            BeginWriteAttribute("onclick", " onclick=\"", 2267, "\"", 2381, 11);
            WriteAttributeValue("", 2277, "EditUserModal(\'", 2277, 15, true);
#nullable restore
#line 54 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 2292, item.NameDoctor, 2292, 16, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 2308, "\',\'", 2308, 3, true);
#nullable restore
#line 54 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 2311, item.LastNameDoctor, 2311, 20, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 2331, "\',\'", 2331, 3, true);
#nullable restore
#line 54 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 2334, item.UserName, 2334, 14, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 2348, "\',\'", 2348, 3, true);
#nullable restore
#line 54 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 2351, item.IdRol, 2351, 11, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 2362, "\',\'", 2362, 3, true);
#nullable restore
#line 54 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 2365, item.IdDoctor, 2365, 14, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 2379, "\')", 2379, 2, true);
            EndWriteAttribute();
            WriteLiteral(@"
                                                data-toggle=""modal"" data-target=""#updateModal"" class=""btn btn-outline-warning"">
                                            <i class=""fas fa-user-edit""></i>
                                        </button>
                                    </td>
                                    <td>

                                       
                                        <button data-toggle=""modal"" data-target=""#deleteModal"" class=""btn btn-outline-danger"">
                                            <i class=""far fa-trash-alt""></i>
                                        </button>
                                        <!-- Modal eliminar-->
                                        <div class=""modal fade"" id=""deleteModal"" tabindex=""-1"" role=""dialog"" aria-labelledby=""exampleModalLabel"" aria-hidden=""true"">
                                            <div class=""modal-dialog"" role=""document"">
                                                <div class=""m");
            WriteLiteral(@"odal-content"">
                                                    <div class=""modal-header text-center"">
                                                        <h5 class=""modal-title  text-red"" id=""exampleModalLabel"">
                                                            <i class=""fa fa-trash"" aria-hidden=""true""></i>
                                                            Eliminando Registro
                                                        </h5>

                                                    </div>
                                                    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2513133", async() => {
                WriteLiteral(@"

                                                        <div class=""modal-body text-center"">
                                                            <h5>
                                                                Estas a punto de ELIMINAR este registro.
                                                            </h5>
                                                            <p class=""text-red"">Esta accion no es REVERSIBLE!!.</p>
                                                            <p>Si estas seguro de lo que intentas realizar presiona Eliminar.</p>

                                                        </div>

                                                        <div class=""modal-footer"">
                                                            <button type=""button"" class=""btn btn-secondary  row-cols-sm-3""
                                                                    data-dismiss=""modal"">
                                                                Cancelar");
                WriteLiteral("\r\n                                                            </button>\r\n                                                            <button");
                BeginWriteAttribute("onclick", " onclick=\"", 5197, "\"", 5234, 3);
                WriteAttributeValue("", 5207, "DeleteUser(\'", 5207, 12, true);
#nullable restore
#line 92 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 5219, item.IdLogin, 5219, 13, false);

#line default
#line hidden
#nullable disable
                WriteAttributeValue("", 5232, "\')", 5232, 2, true);
                EndWriteAttribute();
                WriteLiteral(@" type=""submit"" class=""btn btn-danger  col-sm-9""
                                                                   
                                                                    >
                                                                Eliminar Registro

                                                                
                                                            
                                                            
                                                            </button>
                                                        </div>
                                                    ");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                                                </div>\r\n                                            </div>\r\n                                        </div>\r\n\r\n\r\n                                    </td>\r\n\r\n\r\n\r\n\r\n                                </tr>\r\n");
#nullable restore
#line 114 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"

                                    }

#line default
#line hidden
#nullable disable
#nullable restore
#line 115 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                     
                                }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"

                            </tbody>
                        </table>

                    </div>
                </div>
                <div class=""col-6"">
                    <div class=""table-responsive"">
                        <table class=""table"" id=""idTable"">
                            <caption>Lista de Secretarias</caption>
                            <thead>
                                                          <tr>
                                    <th scope=""col"">Nombre</th>
                                    <th scope=""col"">Apellido</th>
                                    <th scope=""col"">Usuario</th>
                                    <th scope=""col"">Rol</th>
                                    <th scope=""col"">Editar</th>
                                    <th scope=""col"">Eliminar</th>
                                </tr>
                            </thead>
                            <tbody id=""itemTable"">
");
#nullable restore
#line 139 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                 if (ViewBag.listingSecretary != null)
                                {
                                    

#line default
#line hidden
#nullable disable
#nullable restore
#line 141 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                     foreach (var item in ViewBag.listingSecretary)
                                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                        <tr>\r\n                                            <td");
            BeginWriteAttribute("id", " id=\"", 7515, "\"", 7520, 0);
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 144 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                                 Write(item.NameSecretary);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                                            <td");
            BeginWriteAttribute("id", " id=\"", 7595, "\"", 7600, 0);
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 145 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                                 Write(item.LastNameSecretary);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                                            <td");
            BeginWriteAttribute("id", " id=\"", 7679, "\"", 7684, 0);
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 146 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                                 Write(item.UserName);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                                            <td");
            BeginWriteAttribute("id", " id=\"", 7754, "\"", 7759, 0);
            EndWriteAttribute();
            WriteLiteral(">\r\n");
#nullable restore
#line 148 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                                 if (item.IdRol == 1)
                                                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                                    <span class=\"right badge badge-success\">Secretaria</span>\r\n");
#nullable restore
#line 151 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                            </td>\r\n                                            <td>\r\n\r\n                                                <button");
            BeginWriteAttribute("onclick", " onclick=\"", 8207, "\"", 8330, 11);
            WriteAttributeValue("", 8217, "EditUserModal(\'", 8217, 15, true);
#nullable restore
#line 156 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 8232, item.NameSecretary, 8232, 19, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 8251, "\',\'", 8251, 3, true);
#nullable restore
#line 156 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 8254, item.LastNameSecretary, 8254, 23, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 8277, "\',\'", 8277, 3, true);
#nullable restore
#line 156 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 8280, item.UserName, 8280, 14, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 8294, "\',\'", 8294, 3, true);
#nullable restore
#line 156 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 8297, item.IdRol, 8297, 11, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 8308, "\',\'", 8308, 3, true);
#nullable restore
#line 156 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 8311, item.IdSecretary, 8311, 17, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 8328, "\')", 8328, 2, true);
            EndWriteAttribute();
            WriteLiteral(@"
                                                        data-toggle=""modal"" data-target=""#updateModal"" class=""btn btn-outline-warning"">
                                                    <i class=""fas fa-user-edit""></i>
                                                </button>
                                            </td>
                                            <td>

                                                <button data-toggle=""modal"" data-target=""#deleteModal"" class=""btn btn-outline-danger"">
                                                    <i class=""far fa-trash-alt""></i>
                                                </button>
                                                <!-- Modal eliminar-->
                                                <div class=""modal fade"" id=""deleteModal"" tabindex=""-1"" role=""dialog"" aria-labelledby=""exampleModalLabel"" aria-hidden=""true"">
                                                    <div class=""modal-dialog"" role=""document"">
              ");
            WriteLiteral(@"                                          <div class=""modal-content"">
                                                            <div class=""modal-header text-center"">
                                                                <h5 class=""modal-title  text-red"" id=""exampleModalLabel"">
                                                                    <i class=""fa fa-trash"" aria-hidden=""true""></i>
                                                                    Eliminando Registro
                                                                </h5>

                                                            </div>
                                                            ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2525139", async() => {
                WriteLiteral(@"

                                                                <div class=""modal-body text-center"">
                                                                    <h5>
                                                                        Estas a punto de ELIMINAR este registro.
                                                                    </h5>
                                                                    <p class=""text-red"">Esta accion no es REVERSIBLE!!.</p>
                                                                    <p>Si estas seguro de lo que intentas realizar presiona Eliminar.</p>

                                                                </div>

                                                                <div class=""modal-footer"">
                                                                    <button type=""button"" class=""btn btn-secondary  row-cols-sm-3""
                                                                            data-dismiss=""m");
                WriteLiteral("odal\">\r\n                                                                        Cancelar\r\n                                                                    </button>\r\n                                                                    <button");
                BeginWriteAttribute("onclick", " onclick=\"", 11361, "\"", 11398, 3);
                WriteAttributeValue("", 11371, "DeleteUser(\'", 11371, 12, true);
#nullable restore
#line 193 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
WriteAttributeValue("", 11383, item.IdLogin, 11383, 13, false);

#line default
#line hidden
#nullable disable
                WriteAttributeValue("", 11396, "\')", 11396, 2, true);
                EndWriteAttribute();
                WriteLiteral(@" type=""submit"" class=""btn btn-danger  col-sm-9"">
                                                                        Eliminar Registro
                                                                    </button>
                                                                </div>
                                                            ");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
                                                        </div>
                                                    </div>
                                                </div>


                                            </td>

                                        </tr>
");
#nullable restore
#line 206 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"

                                    }

#line default
#line hidden
#nullable disable
#nullable restore
#line 207 "C:\Users\Usuario\source\repos\Doctor2.0\Views\UserManager\UserManager.cshtml"
                                     
                                }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"

                            </tbody>
                        </table>

                    </div>
                </div>
         
        </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <!-- /.content -->
</div><!-- fin del contenedor -->
<!-- Modal Crear nuevo usuario-->
<div class=""modal fade"" id=""UserModal"" tabindex=""-1"" role=""dialog"" aria-labelledby=""exampleModalLabel"" aria-hidden=""true"">
    <div class=""modal-dialog"" role=""document"">
        <div class=""modal-content"">
            <div class=""modal-header"">
                <h5 class=""modal-title"" id=""exampleModalLabel"">Registrar Usuarios</h5>
                <button type=""button"" class=""close"" data-dismiss=""modal"" aria-label=""Close"">
                    <span aria-hidden=""true"">&times;</span>
                </button>
            </div>
            <div class=""modal-body"">

                ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2530356", async() => {
                WriteLiteral(@"
                    <div class=""input-group mb-3"">
                        <div class=""input-group-prepend"">
                            <button class=""btn btn-outline-info"" type=""button"">Tipo de usuario a registrar</button>
                        </div>
                        <select class=""custom-select"" onchange=""GetUserType()"" id=""userType"">
                            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2531011", async() => {
                    WriteLiteral("Seleccione Aqui...");
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                BeginWriteTagHelperAttribute();
                __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
                __tagHelperExecutionContext.AddHtmlAttribute("selected", Html.Raw(__tagHelperStringValueBuffer), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.Minimized);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2532389", async() => {
                    WriteLiteral("Doctor");
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_1.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2533641", async() => {
                    WriteLiteral("Secretaria");
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_2.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_2);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2534897", async() => {
                    WriteLiteral("Administrador");
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_3.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_3);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                        </select>\r\n                    </div>\r\n                    <div class=\"input-group mb-3\" id=\"userTypeSelect\">\r\n                    </div>\r\n\r\n                    <div class=\"form-group row\">\r\n                        <label");
                BeginWriteAttribute("for", " for=\"", 13938, "\"", 13944, 0);
                EndWriteAttribute();
                WriteLiteral(@" class=""col-sm-2 col-form-label"">
                            Correo.:
                        </label>
                        <div class=""col-sm-10"">
                            <input class=""form-control"" name=""_userName"" placeholder=""Correo electronico"">
                        </div>
                        <span id=""errorName"" class=""text-red""></span>
                    </div>
                    <div class=""form-group row"">
                        <label");
                BeginWriteAttribute("for", " for=\"", 14420, "\"", 14426, 0);
                EndWriteAttribute();
                WriteLiteral(@" class=""col-sm-3 col-form-label"">
                            Contrase&ntilde;a.:&nbsp;
                        </label>
                        <div class=""col-sm-9"">
                            <input type=""password"" class=""form-control"" name=""_password"" placeholder=""Contrase&ntilde;a"">
                        </div>
                    </div>
                    <div class=""form-group row"">
                        <label");
                BeginWriteAttribute("for", " for=\"", 14862, "\"", 14868, 0);
                EndWriteAttribute();
                WriteLiteral(@" class=""col-sm-3 col-form-label"">
                            Contrase&ntilde;a.:&nbsp;
                        </label>
                        <div class=""col-sm-9"">
                            <input type=""password"" class=""form-control"" name=""passwordRepeat"" placeholder="" Repita su contrase&ntilde;a"">
                        </div>
                    </div>

                    <div class=""form-group row"">
                        <button type=""button"" class=""btn btn-secondary col-sm-3"" data-dismiss=""modal"">Cancelar</button>
                        <div style=""padding-left:20px""></div>

                        <button id=""btnInsert"" type=""submit"" onclick=""UserDataSend()"" class=""btn btn-success col-sm-8"">Registrar Usuario</button>
                    </div>
                ");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"

            </div>

        </div>
    </div>
</div>

<!-- Modal actualizar cliente-->
<div class=""modal fade"" id=""updateModal"" tabindex=""-1"" role=""dialog"" aria-labelledby=""exampleModalLabel"" aria-hidden=""true"">
    <div class=""modal-dialog"" role=""document"">
        <div class=""modal-content"">
            <div class=""modal-header"">
                <h5 class=""modal-title"" id=""exampleModalLabel"">Actualizar Usuarios</h5>
                <button type=""button"" class=""close"" data-dismiss=""modal"" aria-label=""Close"">
                    <span aria-hidden=""true"">&times;</span>
                </button>
            </div>
            <div class=""modal-body"">

                ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2540405", async() => {
                WriteLiteral("\r\n                    <div class=\"form-group row\">\r\n                        <label");
                BeginWriteAttribute("for", " for=\"", 16492, "\"", 16498, 0);
                EndWriteAttribute();
                WriteLiteral(@" class=""col-sm-2 col-form-label"">
                            Nombre.:
                        </label>
                        <div class=""col-sm-10"">
                            <input class=""form-control"" name=""name"" placeholder=""Nombre"" readonly>
                        </div>
                        <span id=""errorName"" class=""text-red""></span>
                    </div>
                    <div class=""form-group row"">
                        <label");
                BeginWriteAttribute("for", " for=\"", 16966, "\"", 16972, 0);
                EndWriteAttribute();
                WriteLiteral(@" class=""col-sm-2 col-form-label"">
                            Apellido.:
                        </label>
                        <div class=""col-sm-10"">
                            <input class=""form-control"" name=""lastName"" placeholder=""Apellido"" readonly>
                        </div>
                        <span id=""errorName"" class=""text-red""></span>
                    </div>
                    <div class=""form-group row"">
                        <label");
                BeginWriteAttribute("for", " for=\"", 17448, "\"", 17454, 0);
                EndWriteAttribute();
                WriteLiteral(@" class=""col-sm-2 col-form-label"">
                            Usuario.:
                        </label>
                        <div class=""col-sm-10"">
                            <input class=""form-control"" name=""userName"" placeholder=""Nombre de usuario"">
                        </div>
                        <span id=""errorName"" class=""text-red""></span>
                    </div>
                    <div class=""input-group mb-3"">
                        <div class=""input-group-prepend"">
                            <button class=""btn btn-outline-info"" type=""button"">Tipo de usuario a registrar</button>
                        </div>
                        <select class=""custom-select"" onchange=""GetUserType()"" id=""_userType"">
                            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2542987", async() => {
                    WriteLiteral("Seleccione Aqui...");
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                BeginWriteTagHelperAttribute();
                __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
                __tagHelperExecutionContext.AddHtmlAttribute("selected", Html.Raw(__tagHelperStringValueBuffer), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.Minimized);
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_4.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_4);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2544574", async() => {
                    WriteLiteral("Doctor");
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_1.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2545826", async() => {
                    WriteLiteral("Secretaria");
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_2.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_2);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2547082", async() => {
                    WriteLiteral("Administrador");
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_3.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_3);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                        </select>
                    </div>
                    <input type=""hidden"" name=""idHidden""/>
                    <div class=""form-group row"">
                        <button type=""button"" class=""btn btn-secondary col-sm-3"" data-dismiss=""modal"">Cancelar</button>
                        <div style=""padding-left:20px""></div>

                        <button id=""btnInsert"" type=""submit"" onclick=""SendDataUpdate()"" class=""btn btn-success col-sm-8"">Registrar Usuario</button>
                    </div>
                ");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n\r\n            </div>\r\n\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2630b74ff4bf18ce523e94f21440137f425b4b2550022", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
